package delfin_gruppe10.presentation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lukas Bjørnvad
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
         this.buttonGroup1.add(CActive);
         this.buttonGroup1.add(CPassive);
         this.buttonGroup2.add(CExercise);
         this.buttonGroup2.add(CComp);
         
         this.buttonGroup3.add(CActive1);
         this.buttonGroup3.add(CPassive1);
         this.buttonGroup4.add(CExercise1);
         this.buttonGroup4.add(CComp1);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFormand = new javax.swing.JFrame();
        VMembers = new javax.swing.JButton();
        AMemeber = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        pKasserer = new javax.swing.JFrame();
        VMembers2 = new javax.swing.JButton();
        APayment = new javax.swing.JButton();
        Arrears = new javax.swing.JButton();
        Return1 = new javax.swing.JButton();
        pTrainer = new javax.swing.JFrame();
        VMembers3 = new javax.swing.JButton();
        CTeam = new javax.swing.JButton();
        STop5 = new javax.swing.JButton();
        Return2 = new javax.swing.JButton();
        RegisterCP = new javax.swing.JButton();
        ATResult = new javax.swing.JButton();
        ACResult = new javax.swing.JButton();
        MemberL = new javax.swing.JFrame();
        Choice = new javax.swing.JComboBox<>();
        Text = new javax.swing.JTextField();
        Members = new javax.swing.JTextArea();
        Return3 = new javax.swing.JButton();
        AMemberF = new javax.swing.JFrame();
        Text1 = new javax.swing.JTextField();
        Return4 = new javax.swing.JButton();
        Tname = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        Tage = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        Taddress = new javax.swing.JTextField();
        Text4 = new javax.swing.JTextField();
        Tac = new javax.swing.JTextField();
        Text5 = new javax.swing.JTextField();
        Tcity = new javax.swing.JTextField();
        Text6 = new javax.swing.JTextField();
        Tphone = new javax.swing.JTextField();
        Text7 = new javax.swing.JTextField();
        Tmail = new javax.swing.JTextField();
        CPassive = new javax.swing.JRadioButton();
        CActive = new javax.swing.JRadioButton();
        CExercise = new javax.swing.JRadioButton();
        CComp = new javax.swing.JRadioButton();
        Register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        EMemberF = new javax.swing.JFrame();
        Text8 = new javax.swing.JTextField();
        Return5 = new javax.swing.JButton();
        Tname1 = new javax.swing.JTextField();
        Text9 = new javax.swing.JTextField();
        Tage1 = new javax.swing.JTextField();
        Text10 = new javax.swing.JTextField();
        Taddress1 = new javax.swing.JTextField();
        Text11 = new javax.swing.JTextField();
        Tac1 = new javax.swing.JTextField();
        Text12 = new javax.swing.JTextField();
        Tcity1 = new javax.swing.JTextField();
        Text13 = new javax.swing.JTextField();
        Tphone1 = new javax.swing.JTextField();
        Text14 = new javax.swing.JTextField();
        Tmail1 = new javax.swing.JTextField();
        CPassive1 = new javax.swing.JRadioButton();
        CActive1 = new javax.swing.JRadioButton();
        CExercise1 = new javax.swing.JRadioButton();
        CComp1 = new javax.swing.JRadioButton();
        Sedit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Choose = new javax.swing.JFrame();
        jComboBox1 = new javax.swing.JComboBox<>();
        Return6 = new javax.swing.JButton();
        Confirm = new javax.swing.JButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        AddPayment = new javax.swing.JFrame();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Return7 = new javax.swing.JButton();
        ArrearL = new javax.swing.JFrame();
        Choice1 = new javax.swing.JComboBox<>();
        Text15 = new javax.swing.JTextField();
        Members1 = new javax.swing.JTextArea();
        Return8 = new javax.swing.JButton();
        RegisterCM = new javax.swing.JFrame();
        jComboBox3 = new javax.swing.JComboBox<>();
        Return9 = new javax.swing.JButton();
        Confirm1 = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        CompTeamL = new javax.swing.JFrame();
        Choice2 = new javax.swing.JComboBox<>();
        Text16 = new javax.swing.JTextField();
        Members2 = new javax.swing.JTextArea();
        Return10 = new javax.swing.JButton();
        Members3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddCTime = new javax.swing.JFrame();
        Choice3 = new javax.swing.JComboBox<>();
        Return11 = new javax.swing.JButton();
        TDisciplin = new javax.swing.JTextField();
        Text18 = new javax.swing.JTextField();
        Ttime = new javax.swing.JTextField();
        Text19 = new javax.swing.JTextField();
        Tcomp = new javax.swing.JTextField();
        Text20 = new javax.swing.JTextField();
        Text21 = new javax.swing.JTextField();
        Tplacement = new javax.swing.JTextField();
        Confirm2 = new javax.swing.JButton();
        AddTTime = new javax.swing.JFrame();
        Choice4 = new javax.swing.JComboBox<>();
        Return12 = new javax.swing.JButton();
        TDisciplin1 = new javax.swing.JTextField();
        Text22 = new javax.swing.JTextField();
        Ttime1 = new javax.swing.JTextField();
        Text23 = new javax.swing.JTextField();
        Tdate = new javax.swing.JTextField();
        Text24 = new javax.swing.JTextField();
        Confirm3 = new javax.swing.JButton();
        Top5L = new javax.swing.JFrame();
        Choice5 = new javax.swing.JComboBox<>();
        Text17 = new javax.swing.JTextField();
        Members4 = new javax.swing.JTextArea();
        Return13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        inTrainer = new javax.swing.JButton();
        inKasserer = new javax.swing.JButton();
        inFormand = new javax.swing.JButton();

        pFormand.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pFormand.setName("viewMem"); // NOI18N

        VMembers.setText("Vis Medlemmer");
        VMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VMembersActionPerformed(evt);
            }
        });

        AMemeber.setText("Tilføj Medlem");
        AMemeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMemeberActionPerformed(evt);
            }
        });

        Edit.setText("Rediger Medlem");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFormandLayout = new javax.swing.GroupLayout(pFormand.getContentPane());
        pFormand.getContentPane().setLayout(pFormandLayout);
        pFormandLayout.setHorizontalGroup(
            pFormandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormandLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(pFormandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AMemeber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(pFormandLayout.createSequentialGroup()
                .addComponent(Return)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pFormandLayout.setVerticalGroup(
            pFormandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormandLayout.createSequentialGroup()
                .addComponent(Return)
                .addGap(46, 46, 46)
                .addComponent(VMembers)
                .addGap(36, 36, 36)
                .addComponent(AMemeber)
                .addGap(29, 29, 29)
                .addComponent(Edit)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pKasserer.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VMembers2.setText("Vis Medlemer");
        VMembers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VMembers2ActionPerformed(evt);
            }
        });

        APayment.setText("Tilføj Betaling");
        APayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APaymentActionPerformed(evt);
            }
        });

        Arrears.setText("Vis Restance");
        Arrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrearsActionPerformed(evt);
            }
        });

        Return1.setText("Tilbage");
        Return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pKassererLayout = new javax.swing.GroupLayout(pKasserer.getContentPane());
        pKasserer.getContentPane().setLayout(pKassererLayout);
        pKassererLayout.setHorizontalGroup(
            pKassererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKassererLayout.createSequentialGroup()
                .addGroup(pKassererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return1)
                    .addGroup(pKassererLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(pKassererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(APayment, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(VMembers2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Arrears, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pKassererLayout.setVerticalGroup(
            pKassererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKassererLayout.createSequentialGroup()
                .addComponent(Return1)
                .addGap(67, 67, 67)
                .addComponent(VMembers2)
                .addGap(18, 18, 18)
                .addComponent(APayment)
                .addGap(18, 18, 18)
                .addComponent(Arrears)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pTrainer.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VMembers3.setText("Vis Medlemmer");
        VMembers3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VMembers3ActionPerformed(evt);
            }
        });

        CTeam.setText("Vis KHold");
        CTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTeamActionPerformed(evt);
            }
        });

        STop5.setText("Top 5");
        STop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STop5ActionPerformed(evt);
            }
        });

        Return2.setText("Tilbage");
        Return2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return2ActionPerformed(evt);
            }
        });

        RegisterCP.setText("Registrer K");
        RegisterCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCPActionPerformed(evt);
            }
        });

        ATResult.setText("Tilføj TResultat");
        ATResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATResultActionPerformed(evt);
            }
        });

        ACResult.setText("Tilføj KResultat");
        ACResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pTrainerLayout = new javax.swing.GroupLayout(pTrainer.getContentPane());
        pTrainer.getContentPane().setLayout(pTrainerLayout);
        pTrainerLayout.setHorizontalGroup(
            pTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTrainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VMembers3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(STop5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(pTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ACResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ATResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pTrainerLayout.createSequentialGroup()
                .addComponent(Return2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pTrainerLayout.setVerticalGroup(
            pTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTrainerLayout.createSequentialGroup()
                .addComponent(Return2)
                .addGap(67, 67, 67)
                .addGroup(pTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTrainerLayout.createSequentialGroup()
                        .addComponent(VMembers3)
                        .addGap(18, 18, 18)
                        .addComponent(CTeam)
                        .addGap(29, 29, 29)
                        .addComponent(STop5))
                    .addGroup(pTrainerLayout.createSequentialGroup()
                        .addComponent(RegisterCP)
                        .addGap(18, 18, 18)
                        .addComponent(ATResult)
                        .addGap(29, 29, 29)
                        .addComponent(ACResult)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        MemberL.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Choice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Item 2", "Item 3", "Item 4" }));

        Text.setEditable(false);
        Text.setText("Sorter");

        Members.setEditable(false);
        Members.setColumns(20);
        Members.setRows(5);
        Members.setText("Data data data data data ");

        Return3.setText("Tilbage");
        Return3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MemberLLayout = new javax.swing.GroupLayout(MemberL.getContentPane());
        MemberL.getContentPane().setLayout(MemberLLayout);
        MemberLLayout.setHorizontalGroup(
            MemberLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberLLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Choice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(MemberLLayout.createSequentialGroup()
                .addComponent(Return3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Members)
        );
        MemberLLayout.setVerticalGroup(
            MemberLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemberLLayout.createSequentialGroup()
                .addComponent(Return3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MemberLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Choice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Members, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AMemberF.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text1.setEditable(false);
        Text1.setText("Navn:");

        Return4.setText("Tilbage");
        Return4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return4ActionPerformed(evt);
            }
        });

        Text2.setEditable(false);
        Text2.setText("Alder:");
        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });

        Tage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TageActionPerformed(evt);
            }
        });

        Text3.setEditable(false);
        Text3.setText("Adresse:");

        Text4.setEditable(false);
        Text4.setText("Postnr:");

        Text5.setEditable(false);
        Text5.setText("By:");

        Text6.setEditable(false);
        Text6.setText("Telefon:");

        Text7.setEditable(false);
        Text7.setText("Mail:");

        CPassive.setText("Passiv");

        CActive.setText("Activ");

        CExercise.setText("Motion");

        CComp.setText("Konkurrence");

        Register.setText("Registrer");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AMemberFLayout = new javax.swing.GroupLayout(AMemberF.getContentPane());
        AMemberF.getContentPane().setLayout(AMemberFLayout);
        AMemberFLayout.setHorizontalGroup(
            AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMemberFLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AMemberFLayout.createSequentialGroup()
                        .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AMemberFLayout.createSequentialGroup()
                        .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Taddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AMemberFLayout.createSequentialGroup()
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AMemberFLayout.createSequentialGroup()
                                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPassive)
                                    .addComponent(CExercise)))
                            .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AMemberFLayout.createSequentialGroup()
                                    .addComponent(Text5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tcity))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AMemberFLayout.createSequentialGroup()
                                    .addComponent(Text7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tmail))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AMemberFLayout.createSequentialGroup()
                                    .addComponent(Text6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tphone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Return4))
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AMemberFLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CActive)
                                    .addComponent(CComp)
                                    .addComponent(Register, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AMemberFLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        AMemberFLayout.setVerticalGroup(
            AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AMemberFLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tname)
                    .addComponent(CPassive)
                    .addComponent(CActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tage)
                    .addComponent(CExercise)
                    .addComponent(CComp))
                .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AMemberFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Taddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tcity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tphone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Register)
                            .addComponent(Return4))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AMemberFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );

        EMemberF.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text8.setEditable(false);
        Text8.setText("Navn:");

        Return5.setText("Tilbage");
        Return5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return5ActionPerformed(evt);
            }
        });

        Text9.setEditable(false);
        Text9.setText("Alder:");
        Text9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text9ActionPerformed(evt);
            }
        });

        Tage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tage1ActionPerformed(evt);
            }
        });

        Text10.setEditable(false);
        Text10.setText("Adresse:");

        Text11.setEditable(false);
        Text11.setText("Postnr:");

        Text12.setEditable(false);
        Text12.setText("By:");

        Text13.setEditable(false);
        Text13.setText("Telefon:");

        Text14.setEditable(false);
        Text14.setText("Mail:");

        CPassive1.setText("Passiv");

        CActive1.setText("Activ");

        CExercise1.setText("Motion");

        CComp1.setText("Konkurrence");

        Sedit.setText("Edit");
        Sedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EMemberFLayout = new javax.swing.GroupLayout(EMemberF.getContentPane());
        EMemberF.getContentPane().setLayout(EMemberFLayout);
        EMemberFLayout.setHorizontalGroup(
            EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EMemberFLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EMemberFLayout.createSequentialGroup()
                        .addComponent(Text11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tac1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EMemberFLayout.createSequentialGroup()
                        .addComponent(Text10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Taddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EMemberFLayout.createSequentialGroup()
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EMemberFLayout.createSequentialGroup()
                                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tname1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPassive1)
                                    .addComponent(CExercise1)))
                            .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EMemberFLayout.createSequentialGroup()
                                    .addComponent(Text12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tcity1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EMemberFLayout.createSequentialGroup()
                                    .addComponent(Text14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tmail1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EMemberFLayout.createSequentialGroup()
                                    .addComponent(Text13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tphone1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Return5))
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EMemberFLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CActive1)
                                    .addComponent(CComp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EMemberFLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        EMemberFLayout.setVerticalGroup(
            EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EMemberFLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tname1)
                    .addComponent(CPassive1)
                    .addComponent(CActive1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tage1)
                    .addComponent(CExercise1)
                    .addComponent(CComp1))
                .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EMemberFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Taddress1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tac1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tcity1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tphone1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tmail1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EMemberFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sedit)
                            .addComponent(Return5))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EMemberFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );

        Choose.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name1", "Name2" }));

        Return6.setText("Tilbage");
        Return6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return6ActionPerformed(evt);
            }
        });

        Confirm.setText("Vælg");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChooseLayout = new javax.swing.GroupLayout(Choose.getContentPane());
        Choose.getContentPane().setLayout(ChooseLayout);
        ChooseLayout.setHorizontalGroup(
            ChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChooseLayout.createSequentialGroup()
                .addComponent(Return6)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(ChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 67, Short.MAX_VALUE)
                    .addComponent(Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ChooseLayout.setVerticalGroup(
            ChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseLayout.createSequentialGroup()
                .addGroup(ChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Return6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Confirm))
        );

        AddPayment.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name1", "Name2" }));

        jTextField1.setEditable(false);
        jTextField1.setText("Skylder");

        jLabel3.setText("At Betale");

        jTextField2.setText("Beløb");

        jButton1.setText("Betal");

        jButton2.setText("Betal alt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Return7.setText("Tilbage");
        Return7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPaymentLayout = new javax.swing.GroupLayout(AddPayment.getContentPane());
        AddPayment.getContentPane().setLayout(AddPaymentLayout);
        AddPaymentLayout.setHorizontalGroup(
            AddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Return7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(AddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addGroup(AddPaymentLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        AddPaymentLayout.setVerticalGroup(
            AddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPaymentLayout.createSequentialGroup()
                .addGroup(AddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Return7))
                .addGap(1, 1, 1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPaymentLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPaymentLayout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(AddPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        ArrearL.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Choice1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Item 2", "Item 3", "Item 4" }));

        Text15.setEditable(false);
        Text15.setText("Sorter:");

        Members1.setEditable(false);
        Members1.setColumns(20);
        Members1.setRows(5);
        Members1.setText("Data data data data data ");

        Return8.setText("Tilbage");
        Return8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ArrearLLayout = new javax.swing.GroupLayout(ArrearL.getContentPane());
        ArrearL.getContentPane().setLayout(ArrearLLayout);
        ArrearLLayout.setHorizontalGroup(
            ArrearLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArrearLLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Text15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(ArrearLLayout.createSequentialGroup()
                .addComponent(Return8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Members1)
        );
        ArrearLLayout.setVerticalGroup(
            ArrearLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArrearLLayout.createSequentialGroup()
                .addComponent(Return8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ArrearLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Choice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Members1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RegisterCM.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name1", "Name2" }));

        Return9.setText("Tilbage");
        Return9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return9ActionPerformed(evt);
            }
        });

        Confirm1.setText("Tilføj");
        Confirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm1ActionPerformed(evt);
            }
        });

        Remove.setText("Fjern");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterCMLayout = new javax.swing.GroupLayout(RegisterCM.getContentPane());
        RegisterCM.getContentPane().setLayout(RegisterCMLayout);
        RegisterCMLayout.setHorizontalGroup(
            RegisterCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterCMLayout.createSequentialGroup()
                .addGroup(RegisterCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Return9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(RegisterCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Confirm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        RegisterCMLayout.setVerticalGroup(
            RegisterCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterCMLayout.createSequentialGroup()
                .addGroup(RegisterCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Return9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(RegisterCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirm1)
                    .addComponent(Remove)))
        );

        CompTeamL.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Choice2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Item 2", "Item 3", "Item 4" }));

        Text16.setEditable(false);
        Text16.setText("Sorter");

        Members2.setEditable(false);
        Members2.setColumns(20);
        Members2.setRows(5);
        Members2.setText("Data data data data data ");

        Return10.setText("Tilbage");
        Return10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return10ActionPerformed(evt);
            }
        });

        Members3.setEditable(false);
        Members3.setColumns(20);
        Members3.setRows(5);
        Members3.setText("Data data data data data ");

        jLabel4.setText("Senior");

        jLabel5.setText("Junior");

        javax.swing.GroupLayout CompTeamLLayout = new javax.swing.GroupLayout(CompTeamL.getContentPane());
        CompTeamL.getContentPane().setLayout(CompTeamLLayout);
        CompTeamLLayout.setHorizontalGroup(
            CompTeamLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompTeamLLayout.createSequentialGroup()
                .addComponent(Members3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Members2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CompTeamLLayout.createSequentialGroup()
                .addGroup(CompTeamLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return10)
                    .addGroup(CompTeamLLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel5)
                        .addGap(61, 61, 61)
                        .addComponent(Text16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Choice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CompTeamLLayout.setVerticalGroup(
            CompTeamLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompTeamLLayout.createSequentialGroup()
                .addComponent(Return10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CompTeamLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CompTeamLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Members3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Members2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        AddCTime.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Choice3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Navn", "Item 2", "Item 3", "Item 4" }));

        Return11.setText("Tilbage");
        Return11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return11ActionPerformed(evt);
            }
        });

        Text18.setEditable(false);
        Text18.setText("Tid:");
        Text18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text18ActionPerformed(evt);
            }
        });

        Ttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtimeActionPerformed(evt);
            }
        });

        Text19.setEditable(false);
        Text19.setText("Stævne:");

        Text20.setEditable(false);
        Text20.setText("Disciplin:");

        Text21.setEditable(false);
        Text21.setText("Placering:");

        Confirm2.setText("Tilføj");
        Confirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCTimeLayout = new javax.swing.GroupLayout(AddCTime.getContentPane());
        AddCTime.getContentPane().setLayout(AddCTimeLayout);
        AddCTimeLayout.setHorizontalGroup(
            AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCTimeLayout.createSequentialGroup()
                .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return11)
                    .addGroup(AddCTimeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddCTimeLayout.createSequentialGroup()
                                .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Choice3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Text19)
                                        .addComponent(Text20, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Text18, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(Text21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tplacement)
                                    .addComponent(Ttime, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(TDisciplin, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(Tcomp, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addComponent(Confirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        AddCTimeLayout.setVerticalGroup(
            AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCTimeLayout.createSequentialGroup()
                .addComponent(Return11)
                .addGap(23, 23, 23)
                .addComponent(Choice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TDisciplin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tcomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddCTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tplacement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Confirm2)
                .addGap(39, 39, 39))
        );

        AddTTime.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Choice4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Navn", "Item 2", "Item 3", "Item 4" }));

        Return12.setText("Tilbage");
        Return12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return12ActionPerformed(evt);
            }
        });

        Text22.setEditable(false);
        Text22.setText("Tid:");
        Text22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text22ActionPerformed(evt);
            }
        });

        Ttime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ttime1ActionPerformed(evt);
            }
        });

        Text23.setEditable(false);
        Text23.setText("Dato:");

        Text24.setEditable(false);
        Text24.setText("Disciplin:");

        Confirm3.setText("Tilføj");
        Confirm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddTTimeLayout = new javax.swing.GroupLayout(AddTTime.getContentPane());
        AddTTime.getContentPane().setLayout(AddTTimeLayout);
        AddTTimeLayout.setHorizontalGroup(
            AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTTimeLayout.createSequentialGroup()
                .addGroup(AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return12)
                    .addGroup(AddTTimeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddTTimeLayout.createSequentialGroup()
                                .addGroup(AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Choice4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Text23)
                                    .addComponent(Text24, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text22, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(3, 3, 3)
                                .addGroup(AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Ttime1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(TDisciplin1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(Tdate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addComponent(Confirm3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        AddTTimeLayout.setVerticalGroup(
            AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddTTimeLayout.createSequentialGroup()
                .addComponent(Return12)
                .addGap(23, 23, 23)
                .addComponent(Choice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TDisciplin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ttime1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddTTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tdate))
                .addGap(18, 18, 18)
                .addComponent(Confirm3)
                .addContainerGap())
        );

        Top5L.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Choice5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disciplin", "Item 2", "Item 3", "Item 4" }));

        Text17.setEditable(false);
        Text17.setText("Sorter");

        Members4.setEditable(false);
        Members4.setColumns(20);
        Members4.setRows(5);
        Members4.setText("Data data data data data ");

        Return13.setText("Tilbage");
        Return13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Top5LLayout = new javax.swing.GroupLayout(Top5L.getContentPane());
        Top5L.getContentPane().setLayout(Top5LLayout);
        Top5LLayout.setHorizontalGroup(
            Top5LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Top5LLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Text17, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Choice5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(Top5LLayout.createSequentialGroup()
                .addComponent(Return13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Members4)
        );
        Top5LLayout.setVerticalGroup(
            Top5LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Top5LLayout.createSequentialGroup()
                .addComponent(Return13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Top5LLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Choice5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Members4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 240, 240));

        inTrainer.setText("Træner");
        inTrainer.setMaximumSize(new java.awt.Dimension(100, 50));
        inTrainer.setMinimumSize(new java.awt.Dimension(100, 50));
        inTrainer.setPreferredSize(new java.awt.Dimension(100, 50));
        inTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTrainerActionPerformed(evt);
            }
        });

        inKasserer.setText("Kasserer");
        inKasserer.setMaximumSize(new java.awt.Dimension(100, 50));
        inKasserer.setMinimumSize(new java.awt.Dimension(100, 50));
        inKasserer.setPreferredSize(new java.awt.Dimension(100, 50));
        inKasserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inKassererActionPerformed(evt);
            }
        });

        inFormand.setText("Formand");
        inFormand.setMaximumSize(new java.awt.Dimension(100, 50));
        inFormand.setMinimumSize(new java.awt.Dimension(100, 50));
        inFormand.setPreferredSize(new java.awt.Dimension(100, 50));
        inFormand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inFormandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inFormand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inKasserer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inFormand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inKasserer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTrainerActionPerformed
               
this.pTrainer.setVisible(true);
this.pTrainer.setSize(400, 300);
this.dispose();
        
    }//GEN-LAST:event_inTrainerActionPerformed

    private void AMemeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMemeberActionPerformed
    
this.AMemberF.setVisible(true);
this.AMemberF.setSize(500, 400);
this.pFormand.dispose();  
         
    }//GEN-LAST:event_AMemeberActionPerformed

    private void inKassererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inKassererActionPerformed
              
this.pKasserer.setVisible(true);
this.pKasserer.setSize(400, 300);
this.dispose();
    }//GEN-LAST:event_inKassererActionPerformed

    private void inFormandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inFormandActionPerformed

   
this.pFormand.setVisible(true);
this.pFormand.setSize(400, 300);
this.dispose();
    }//GEN-LAST:event_inFormandActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        this.Choose.setVisible(true);
        this.Choose.setSize(200, 150);
        this.pFormand.dispose();
    }//GEN-LAST:event_EditActionPerformed

    private void APaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APaymentActionPerformed
    this.AddPayment.setVisible(true);
    this.AddPayment.setSize(250, 200);
    this.pKasserer.dispose();
    }//GEN-LAST:event_APaymentActionPerformed

    private void ArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrearsActionPerformed
    this.ArrearL.setVisible(true);
    this.ArrearL.setSize(400, 300);
    this.pKasserer.dispose();
    }//GEN-LAST:event_ArrearsActionPerformed

    private void RegisterCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCPActionPerformed
        this.RegisterCM.setVisible(true);
        this.RegisterCM.setSize(200, 100);
        this.pTrainer.dispose();
    }//GEN-LAST:event_RegisterCPActionPerformed

    private void ATResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATResultActionPerformed
        this.AddTTime.setVisible(true);
        this.AddTTime.setSize(400, 300);
        this.pTrainer.dispose();
    }//GEN-LAST:event_ATResultActionPerformed

    private void VMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VMembersActionPerformed

this.MemberL.setVisible(true);
this.MemberL.setSize(400, 300);
this.pFormand.dispose();
    }//GEN-LAST:event_VMembersActionPerformed

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    private void TageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TageActionPerformed

    private void Return4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return4ActionPerformed

       this.pFormand.setVisible(true);
       this.pFormand.setSize(400, 300);
       this.AMemberF.dispose();
    }//GEN-LAST:event_Return4ActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed

       this.setVisible(true);
       this.setSize(400, 300);
       this.pFormand.dispose();
    }//GEN-LAST:event_ReturnActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        this.jLabel1.setText("Registreret");
    }//GEN-LAST:event_RegisterActionPerformed

    private void Return5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return5ActionPerformed
       this.Choose.setVisible(true);
       this.Choose.setSize(200, 150);
       this.EMemberF.dispose();
    }//GEN-LAST:event_Return5ActionPerformed

    private void Text9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text9ActionPerformed

    private void Tage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tage1ActionPerformed

    private void SeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeditActionPerformed
         this.jLabel2.setText("Ændret");
    }//GEN-LAST:event_SeditActionPerformed

    private void Return6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return6ActionPerformed
        this.pFormand.setVisible(true);
        this.pFormand.setSize(400, 300);
        this.Choose.dispose();
    }//GEN-LAST:event_Return6ActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        this.EMemberF.setVisible(true);
        this.EMemberF.setSize(500, 400);
        this.Choose.dispose();
    }//GEN-LAST:event_ConfirmActionPerformed

    private void Return3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return3ActionPerformed
        this.setVisible(true);
        this.setSize(400, 300);
        this.MemberL.dispose();
    }//GEN-LAST:event_Return3ActionPerformed

    private void Return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return1ActionPerformed
        this.setVisible(true);
        this.setSize(400, 300);
        this.pKasserer.dispose();
    }//GEN-LAST:event_Return1ActionPerformed

    private void VMembers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VMembers2ActionPerformed
       this.MemberL.setVisible(true);
this.MemberL.setSize(400, 300);
this.pKasserer.dispose();
    }//GEN-LAST:event_VMembers2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Return7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return7ActionPerformed
    this.pKasserer.setVisible(true);
    this.pKasserer.setSize(400, 300);
    this.AddPayment.dispose();
    }//GEN-LAST:event_Return7ActionPerformed

    private void Return8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return8ActionPerformed
        this.pKasserer.setVisible(true);
        this.pKasserer.setSize(400, 300); 
        this.ArrearL.dispose();
    }//GEN-LAST:event_Return8ActionPerformed

    private void Return9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return9ActionPerformed
       this.pTrainer.setVisible(true);
        this.pTrainer.setSize(400, 300);
        this.RegisterCM.dispose();  
    }//GEN-LAST:event_Return9ActionPerformed

    private void Confirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm1ActionPerformed
        this.jLabel3.setText("Tilføjet");
    }//GEN-LAST:event_Confirm1ActionPerformed

    private void Return10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return10ActionPerformed
        this.pTrainer.setVisible(true);
        this.pTrainer.setSize(400, 300);
        this.CompTeamL.dispose();
    }//GEN-LAST:event_Return10ActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
       this.jLabel3.setText("Fjernet");
    }//GEN-LAST:event_RemoveActionPerformed

    private void Return11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return11ActionPerformed
        this.pTrainer.setVisible(true);
        this.pTrainer.setSize(400, 300);
        this.AddCTime.dispose();
    }//GEN-LAST:event_Return11ActionPerformed

    private void Text18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text18ActionPerformed

    private void TtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtimeActionPerformed

    private void Confirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm2ActionPerformed

    private void Return12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return12ActionPerformed
        this.pTrainer.setVisible(true);
        this.pTrainer.setSize(400, 300);
        this.AddTTime.dispose();
    }//GEN-LAST:event_Return12ActionPerformed

    private void Text22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text22ActionPerformed

    private void Ttime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ttime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ttime1ActionPerformed

    private void Confirm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm3ActionPerformed

    private void Return13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return13ActionPerformed
        this.pTrainer.setVisible(true);
        this.pTrainer.setSize(400, 300);
        this.Top5L.dispose();
    }//GEN-LAST:event_Return13ActionPerformed

    private void VMembers3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VMembers3ActionPerformed
        this.MemberL.setVisible(true);
        this.MemberL.setSize(400, 300);
        this.pTrainer.dispose();
    }//GEN-LAST:event_VMembers3ActionPerformed

    private void CTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTeamActionPerformed
        this.CompTeamL.setVisible(true);
        this.CompTeamL.setSize(400, 300);
        this.pTrainer.dispose();
    }//GEN-LAST:event_CTeamActionPerformed

    private void STop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STop5ActionPerformed
        this.Top5L.setVisible(true);
        this.Top5L.setSize(450, 400);
        this.pTrainer.dispose();
    }//GEN-LAST:event_STop5ActionPerformed

    private void ACResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACResultActionPerformed
        this.AddCTime.setVisible(true);
        this.AddCTime.setSize(400, 300);
        this.pTrainer.dispose();
    }//GEN-LAST:event_ACResultActionPerformed

    private void Return2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return2ActionPerformed
        this.setVisible(true);
        this.setSize(400, 300);
        this.pTrainer.dispose();
    }//GEN-LAST:event_Return2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACResult;
    private javax.swing.JFrame AMemberF;
    private javax.swing.JButton AMemeber;
    private javax.swing.JButton APayment;
    private javax.swing.JButton ATResult;
    private javax.swing.JFrame AddCTime;
    private javax.swing.JFrame AddPayment;
    private javax.swing.JFrame AddTTime;
    private javax.swing.JFrame ArrearL;
    private javax.swing.JButton Arrears;
    private javax.swing.JRadioButton CActive;
    private javax.swing.JRadioButton CActive1;
    private javax.swing.JRadioButton CComp;
    private javax.swing.JRadioButton CComp1;
    private javax.swing.JRadioButton CExercise;
    private javax.swing.JRadioButton CExercise1;
    private javax.swing.JRadioButton CPassive;
    private javax.swing.JRadioButton CPassive1;
    private javax.swing.JButton CTeam;
    private javax.swing.JComboBox<String> Choice;
    private javax.swing.JComboBox<String> Choice1;
    private javax.swing.JComboBox<String> Choice2;
    private javax.swing.JComboBox<String> Choice3;
    private javax.swing.JComboBox<String> Choice4;
    private javax.swing.JComboBox<String> Choice5;
    private javax.swing.JFrame Choose;
    private javax.swing.JFrame CompTeamL;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Confirm1;
    private javax.swing.JButton Confirm2;
    private javax.swing.JButton Confirm3;
    private javax.swing.JFrame EMemberF;
    private javax.swing.JButton Edit;
    private javax.swing.JFrame MemberL;
    private javax.swing.JTextArea Members;
    private javax.swing.JTextArea Members1;
    private javax.swing.JTextArea Members2;
    private javax.swing.JTextArea Members3;
    private javax.swing.JTextArea Members4;
    private javax.swing.JButton Register;
    private javax.swing.JFrame RegisterCM;
    private javax.swing.JButton RegisterCP;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Return;
    private javax.swing.JButton Return1;
    private javax.swing.JButton Return10;
    private javax.swing.JButton Return11;
    private javax.swing.JButton Return12;
    private javax.swing.JButton Return13;
    private javax.swing.JButton Return2;
    private javax.swing.JButton Return3;
    private javax.swing.JButton Return4;
    private javax.swing.JButton Return5;
    private javax.swing.JButton Return6;
    private javax.swing.JButton Return7;
    private javax.swing.JButton Return8;
    private javax.swing.JButton Return9;
    private javax.swing.JButton STop5;
    private javax.swing.JButton Sedit;
    private javax.swing.JTextField TDisciplin;
    private javax.swing.JTextField TDisciplin1;
    private javax.swing.JTextField Tac;
    private javax.swing.JTextField Tac1;
    private javax.swing.JTextField Taddress;
    private javax.swing.JTextField Taddress1;
    private javax.swing.JTextField Tage;
    private javax.swing.JTextField Tage1;
    private javax.swing.JTextField Tcity;
    private javax.swing.JTextField Tcity1;
    private javax.swing.JTextField Tcomp;
    private javax.swing.JTextField Tdate;
    private javax.swing.JTextField Text;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text10;
    private javax.swing.JTextField Text11;
    private javax.swing.JTextField Text12;
    private javax.swing.JTextField Text13;
    private javax.swing.JTextField Text14;
    private javax.swing.JTextField Text15;
    private javax.swing.JTextField Text16;
    private javax.swing.JTextField Text17;
    private javax.swing.JTextField Text18;
    private javax.swing.JTextField Text19;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text20;
    private javax.swing.JTextField Text21;
    private javax.swing.JTextField Text22;
    private javax.swing.JTextField Text23;
    private javax.swing.JTextField Text24;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    private javax.swing.JTextField Text5;
    private javax.swing.JTextField Text6;
    private javax.swing.JTextField Text7;
    private javax.swing.JTextField Text8;
    private javax.swing.JTextField Text9;
    private javax.swing.JTextField Tmail;
    private javax.swing.JTextField Tmail1;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tname1;
    private javax.swing.JFrame Top5L;
    private javax.swing.JTextField Tphone;
    private javax.swing.JTextField Tphone1;
    private javax.swing.JTextField Tplacement;
    private javax.swing.JTextField Ttime;
    private javax.swing.JTextField Ttime1;
    private javax.swing.JButton VMembers;
    private javax.swing.JButton VMembers2;
    private javax.swing.JButton VMembers3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton inFormand;
    private javax.swing.JButton inKasserer;
    private javax.swing.JButton inTrainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JFrame pFormand;
    private javax.swing.JFrame pKasserer;
    private javax.swing.JFrame pTrainer;
    // End of variables declaration//GEN-END:variables
}
